[package]
name = "reach"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
camino = "1.2.1"
clap = { version = "4.5.53", features = ["derive", "env"] }
etcetera = "0.11.0"
jiff = "0.2.16"
parse_datetime = "0.13.2"
pathdiff = { version = "0.2.3", features = ["camino"] }
rusqlite = { version = "0.38.0", features = ["bundled", "jiff"] }

[lints]
clippy.pedantic = { level = "warn", priority = -1 }
clippy.redundant_closure = "allow"

[profile.profile]
inherits = "release"
debug = "full"
